### PR TITLE
identify samples usable with Docker Dev Environments

### PR DESCRIPTION
**Pull request by glours**
Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

### CODE REVIEW

**Review by nicksieger — CHANGES_REQUESTED** [review]
English nit on the alt text, can you change "usable with dev environments" to "Use with Docker Dev Environments"? I think the imperative verb reads a bit better.

Also for @SurbhiSGupta I think the devenvs svg icon here might eventually be replaced with the button that you're working on.

**Review by nicksieger — APPROVED** [review]

**Comment by hyu** [comment]
Thanks @glours, this is great! I have two non-blocking nitpicks:

### 1. Adjust icon size and alignment:
I recommend:
``


Before:
image

After:
image


&nbsp; 
&nbsp; 

### 2. Move Icon explanation closer to usage

Before:
image

After, Proposed: 
image

**Comment by glours** [comment]
@hyu changes done, if this is fine for you I'll merge the PR

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
