### PR TITLE
nginx-aspnet-mysql: add dev envs configuration

### PR DESCRIPTION
**Pull request by milas**
* Fix/enable MySQL/MariaDB health check
* Refactor `Dockerfile` for use as Compose app as well as with
  dev envs

### CODE REVIEW

**Comment by laurazard** [comment]
I'm getting an error setting it up from your branch with:

```
invalid interpolation format for services.db.healthcheck.test.[]: "mysqladmin ping -h 127.0.0.1 --password=\"$(cat /run/secrets/db-password)\" --silent". You may need to escape any $ with another $
exit status 15
```

is it just me?

**Comment by StefanScherer** [comment]
I have the same error message, both on Mac M1 and Mac Intel.

**Comment by milas** [comment]
Oof, yeah, I'm seeing the same thing. I removed the health check from the `.docker/docker-compose.yaml` variant for dev envs - it was actually previously commented out everywhere, so it's not any worse than previously IMO.

**Review by StefanScherer — APPROVED** [review]
Looks good now, it works!

**Review by laurazard — APPROVED** [review]

**Review by glours — APPROVED** [review]
LGTM

**Pull request merged**
