### PR TITLE
update php version to 8.0.3

### PR DESCRIPTION
**Pull request by spamr**
current stable version: 8.0.3 / 4 March 2021

### CODE REVIEW

**Comment by spamr** [comment]
Sorry for the additional commits. working on a sample application for nginx-php-mysql. That will not be included in this pull request.

**Comment by spamr** [comment]
this pull request is back to the original state and **ready to be reviewed**

**Review by samuelludwig — APPROVED** [review]
I don't see a reason to not make this change, hopefully this gets merged in 👍

**Review by aiordache — APPROVED** [review]
Thank you

**Pull request merged**
