### PR TITLE
Add compose samples from docs

### PR DESCRIPTION
**Pull request by StefanScherer**
This PR moves three quickstart samples from docs to this repo. These samples describe which files to create and don't have them already created like all the other awesome-compose sample folders. But they are still a good starting point.

JIRA: https://docker.atlassian.net/browse/EN-293

Corresponding docs PR: https://github.com/docker/docs/pull/16001

### CODE REVIEW

**Review by glours — CHANGES_REQUESTED** [review]
Can we use a more meaningful name for the directory such as `official-documentation` or `documentation-samples` or `official-documentation-samples`? 
Can you also add a new section in the main `README.md` to explain the content of the folder and provide a direct link to the directory?

**Comment by StefanScherer** [comment]
Thanks @glours, yes to both, will change the folder name and add a section in the main README.

**Comment by StefanScherer** [comment]
@glours PTAL. I've added a link to the `official-documentation-samples`.

**Review by glours — APPROVED** [review]
LGTM, thanks @StefanScherer !

**Pull request merged**
